### ISSUE TITLE
Chassis-id set commands with a timeout of greater than 255 are turning the led on indefinitely.

### ISSUE THREAD

**Issue by ericho** [intel-ctrlsys/sensys#5]
## Description
After 255 seconds, octl and ipmiutil show the target system led as having turned back off, but in reality the led remains on indefinitely.

## Expected Behavior
The LED shall turn off after timeout.

## Actual Behavior
The LED keeps on indefinitely

## Steps to Reproduce the Problem

  1. Run the following command
```
./octl chassis-id enable 300 mymachine
```

## Specifications

  - **Version**: v0.29
  - **Platform**: CentOS 7.2
  - **Component**: Chassis-id

**Comment by vrescami** [comment]
There are some things that makes me think it is outside the scope:

1. There's a limit check on octl that won't let you use a value greater than 255 for chassis-id command. You can specify a value greater than 255 in the CLI, but chassis_id feature will use 255 instead.
2. In order to turn the LED ON indefinitely, a flag must be set on the IPMI message. So, the value of the seconds shouldn't affect this property. This flag is only set when using the enable command without seconds value: 
```./octl chassis-id enable mymachine```

3. I executed the following line on the machine where this issue fist appear.
```./octl chassis-id enable 300 mymachine```
After 255 seconds I requested the state of the LED using ipmiutils and it shows that the LED is OFF. The issue is that if you look at the chassis, the LED is actually ON.

4. I've not been able to reproduce the issue on any other machine but the one that raised this bug.

**Comment by ericho** [comment]
Thanks @VicsEscamilla 

This seems to be a hardware dependent issue and that [is already documented](https://intel-ctrlsys.github.io/sensys/3-Sensys-User-Guide/3.7-octl.html#chassis-id). 

```
NOTE: This command is hardware-dependent and it might not be supported on all platforms.
```

We'll probably need to gather more information on different platforms but that, as you mentioned, is outside of the scope.
